---

- hosts: all
  vars:
    sudo_sudoersd_managed: no
    sudo_defaults__default:
      - '!visiblepw'
      - always_set_home
      - env_reset
      - env_keep  = "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
      - env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
      - env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
      - env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
      - env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
      - secure_path = /sbin:/bin:/usr/sbin:/usr/bin

  pre_tasks:
    - name: Load a variable file based on the OS type
      include_vars: "{{ ansible_os_family }}.yml"

  roles:
    - jtyr.sudo
